# Generated by Django 3.2.3 on 2021-06-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='total_amt',
            field=models.IntegerField(default=0, verbose_name='total amount'),
            preserve_default=False,
        ),
    ]
