# Generated by Django 3.2.5 on 2021-07-06 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=30)),
                ('category', models.CharField(default='fantasy', max_length=255)),
                ('book_state', models.CharField(default='old', max_length=255)),
                ('is_signed_by_author', models.BooleanField(default=False, verbose_name='is book signed by Author?')),
                ('is_collection', models.BooleanField(default=False, verbose_name='is part of collection')),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='book_default.png', upload_to='books', verbose_name='Main Image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='books', verbose_name='image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='books', verbose_name='image 3')),
                ('is_shared', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='PurchaseModel',
        ),
    ]
