# Generated by Django 3.2.5 on 2021-07-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contact_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
    ]
